#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Owlsay
# Copyright (C) 2016  Honza Pokorny <me@honza.ca>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import textwrap

OWL = """
     \        ,   .   ,
      \       )-_\"\"\"_-(
       \     ./ o\ /o \.
        \   . \__/ \__/ .
         \  ...   V   ...
            ... - - - ...
             .   - -   .
              `-.....-´
"""


def textbox(text, width=60):
    if len(text) < width:
        width = len(text) + 1

    boundary = ' ' + ('-' * (width + 1))
    r = [boundary]
    lines = textwrap.wrap(text, width)

    for line in lines:
        line = line.ljust(width - 1)
        r.append('| %s |' % line)

    r.append(boundary)
    r = '\n'.join(r)
    return r


def main(text):
    print(textbox(text))
    print(OWL)


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print('Usage: owlsay <message>')
        sys.exit(1)

    main(sys.argv[1])
